---

- name: Disable default site
  command: /usr/sbin/a2dissite 000-default.conf removes=/etc/apache2/sites-enabled/000-default.conf
  sudo: yes
  notify:
    - reload apache

  
- name: Set basic Apache config
  template: src=apache2.conf.j2 dest=/etc/apache2/apache2.conf
  sudo: yes
  notify:
    - reload apache


- name: Setting Apache Prefork MPM defaults
  lineinfile: 
    dest=/etc/apache2/mods-available/mpm_prefork.conf
    regexp="{{ item.key }}"
    line="{{ item.key }} {{ item.value }}"
  with_dict:
    default_mpm_prefork_conf
  sudo: yes
  when: mpm_prefork_conf[item["key"]] is not defined


- name: Setting Apache Prefork MPM config
  lineinfile: 
    dest=/etc/apache2/mods-available/mpm_prefork.conf
    regexp="{{ item.key }}"
    line="{{ item.key }} {{ item.value }}"
  with_dict:
    mpm_prefork_conf
  sudo: yes
